// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado atual (id, email) para verificar a conex\xE3o MCP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.6";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4";
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  return createClient(env.SUPABASE_URL, env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes da ag\xEAncia (respeita RLS do usu\xE1rio logado). Filtra por status opcional e limita resultados.",
  inputSchema: {
    status: z.enum(["active", "inactive"]).optional().describe("Filtrar por status do cliente."),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de clientes retornados (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, company_name, contact_name, contact_phone, status, contract_value, payment_type, first_payment_date, last_payment_date").order("company_name", { ascending: true }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.6";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4";
function supabaseForUser2(ctx) {
  const env = globalThis.process?.env ?? {};
  return createClient2(env.SUPABASE_URL, env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_client_default = defineTool3({
  name: "get_client",
  title: "Obter cliente",
  description: "Retorna dados completos de um cliente por id, incluindo contas de an\xFAncio vinculadas.",
  inputSchema: {
    clientId: z2.string().uuid().describe("UUID do cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ clientId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const [{ data: client, error: clientError }, { data: accounts, error: accountsError }] = await Promise.all([
      supabase.from("clients").select("*").eq("id", clientId).maybeSingle(),
      supabase.from("client_accounts").select("id, account_id, account_name, platform, status, is_primary").eq("client_id", clientId)
    ]);
    if (clientError) return { content: [{ type: "text", text: `Erro: ${clientError.message}` }], isError: true };
    if (!client) return { content: [{ type: "text", text: "Cliente n\xE3o encontrado" }], isError: true };
    const payload = { client, accounts: accountsError ? [] : accounts ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-budget-reviews.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.6";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4";
function supabaseForUser3(ctx) {
  const env = globalThis.process?.env ?? {};
  return createClient3(env.SUPABASE_URL, env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_budget_reviews_default = defineTool4({
  name: "list_budget_reviews",
  title: "Listar revis\xF5es de or\xE7amento",
  description: "Lista revis\xF5es di\xE1rias de or\xE7amento (Meta/Google) com filtros por cliente, plataforma e data.",
  inputSchema: {
    clientId: z3.string().uuid().optional().describe("Filtrar por UUID do cliente."),
    platform: z3.enum(["meta", "google"]).optional().describe("Filtrar por plataforma."),
    reviewDate: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data da revis\xE3o no formato YYYY-MM-DD. Se omitido, retorna as mais recentes."),
    limit: z3.number().int().min(1).max(200).optional().describe("M\xE1ximo de linhas (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ clientId, platform, reviewDate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("budget_reviews").select("id, client_id, platform, account_id, review_date, daily_budget_current, total_spent, last_five_days_spent, using_custom_budget, custom_budget_amount").order("review_date", { ascending: false }).limit(limit ?? 50);
    if (clientId) query = query.eq("client_id", clientId);
    if (platform) query = query.eq("platform", platform);
    if (reviewDate) query = query.eq("review_date", reviewDate);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "socrnutfpqtcjmetskta";
var mcp_default = defineMcp({
  name: "muran-app-mcp",
  title: "Muran App MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Muran APP para consultar clientes, contas de an\xFAncio e revis\xF5es di\xE1rias de or\xE7amento (Meta Ads e Google Ads). Todas as leituras respeitam o usu\xE1rio autenticado e as pol\xEDticas de RLS do Supabase.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_clients_default, get_client_default, list_budget_reviews_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
