// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = "https://socrnutfpqtcjmetskta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvY3JudXRmcHF0Y2ptZXRza3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDg1OTMsImV4cCI6MjA1MzkyNDU5M30.yFkP90puucdc1qxlIOs3Hp4V18_LKea2mf6blmJ9Rpw";

export const SUPABASE_AUTH_STORAGE_KEY = 'muran-auth-token';

// Native fetch captured in index.html BEFORE any external script (lovable.js)
// could proxy window.fetch. Used as bypass for the proxy when it breaks auth.
const nativeFetch: typeof fetch =
  (typeof window !== 'undefined' && (window as any).__nativeFetch) ||
  (typeof window !== 'undefined' ? window.fetch.bind(window) : fetch);

let lastNetworkErrorAt = 0;
let invalidRefreshTokenDetected = false;

/**
 * Helper público: limpa apenas a sessão local do Supabase, sem zerar
 * todo o localStorage (que apagaria também temas, prefs, caches, etc).
 */
export const clearSupabaseLocalSession = () => {
  try {
    Object.keys(localStorage).forEach((k) => {
      if (k === SUPABASE_AUTH_STORAGE_KEY || k.startsWith('sb-') || k.startsWith('supabase.')) {
        localStorage.removeItem(k);
      }
    });
    Object.keys(sessionStorage).forEach((k) => {
      if (k === SUPABASE_AUTH_STORAGE_KEY || k.startsWith('sb-') || k.startsWith('supabase.')) {
        sessionStorage.removeItem(k);
      }
    });
    lastNetworkErrorAt = 0;
    invalidRefreshTokenDetected = false;
  } catch (e) {
    logger.error('Falha ao limpar sessão local do Supabase:', e);
  }
};

export const getLastSupabaseNetworkErrorAt = () => lastNetworkErrorAt;
export const wasInvalidRefreshTokenDetected = () => invalidRefreshTokenDetected;

/**
 * Fetch para Supabase:
 * - Para QUALQUER request de /auth/v1/, usa SEMPRE nativeFetch (bypass do proxy lovable.js).
 *   Isso elimina a regressão conhecida do Preview que quebra POSTs de auth.
 * - Detecta respostas com refresh_token inválido e auto-limpa a sessão local
 *   para impedir loops infinitos de retry.
 */
const fetchWithDiagnostics: typeof fetch = async (input, init) => {
  const url = typeof input === 'string' ? input : (input as Request).url;
  const isSupabaseAuth = typeof url === 'string' && url.includes('/auth/v1/');
  const isRefreshToken = typeof url === 'string' && url.includes('/auth/v1/token');

  if (isSupabaseAuth) {
    // SEMPRE usa nativeFetch para auth — não confia no fetch do escopo (pode estar proxado).
    try {
      const res = await nativeFetch(input, init);

      // Detecta refresh_token inválido → limpa sessão para parar o loop
      if (isRefreshToken && (res.status === 400 || res.status === 401)) {
        try {
          const cloned = res.clone();
          const body = await cloned.json();
          const code = body?.error_code || body?.error || body?.code || '';
          const msg = (body?.error_description || body?.msg || '').toLowerCase();
          if (
            code === 'refresh_token_not_found' ||
            code === 'invalid_grant' ||
            msg.includes('refresh token') ||
            msg.includes('invalid grant')
          ) {
            invalidRefreshTokenDetected = true;
            logger.warn('🧹 Refresh token inválido detectado, limpando sessão local para parar loop.');
            clearSupabaseLocalSession();
          }
        } catch {
          // body não-JSON, ignora
        }
      }

      return res;
    } catch (err) {
      lastNetworkErrorAt = Date.now();
      logger.error('🚫 Falha de REDE (nativeFetch) ao chamar Supabase auth:', { url });
      throw err;
    }
  }

  // Demais requests (REST, edge functions etc.) seguem com fetch padrão
  try {
    return await fetch(input, init);
  } catch (err) {
    throw err;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: SUPABASE_AUTH_STORAGE_KEY,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: {
      getItem: (key) => {
        try {
          return localStorage.getItem(key);
        } catch {
          return null;
        }
      },
      setItem: (key, value) => {
        try {
          localStorage.setItem(key, value);
        } catch (error) {
          logger.error('Erro ao salvar dado da storage:', error);
        }
      },
      removeItem: (key) => {
        try {
          localStorage.removeItem(key);
        } catch (error) {
          logger.error('Erro ao remover dado da storage:', error);
        }
      },
    },
  },
  global: {
    fetch: fetchWithDiagnostics,
  },
});

// Tenta remover service workers antigos que possam estar interceptando requests
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  navigator.serviceWorker.getRegistrations().then((regs) => {
    regs.forEach((reg) => {
      logger.warn('🧹 Removendo service worker antigo:', reg.scope);
      reg.unregister();
    });
  }).catch(() => {});
}
