
// Lista de emojis com seus identificadores e rótulos
export const BADGE_ICONS = [
  { icon: "🏆", name: "trophy", label: "Troféu" },
  { icon: "⭐", name: "star", label: "Estrela" },
  { icon: "🎖️", name: "medal", label: "Medalha" },
  { icon: "👑", name: "crown", label: "Coroa" },
  { icon: "❤️", name: "heart", label: "Coração" },
  { icon: "🛡️", name: "shield", label: "Escudo" },
  { icon: "🔖", name: "bookmark", label: "Marcador" },
  { icon: "🎯", name: "target", label: "Alvo" },
  { icon: "✨", name: "sparkles", label: "Brilhos" },
  { icon: "⚡", name: "zap", label: "Raio" },
  { icon: "🎀", name: "ribbon", label: "Fita" },
  { icon: "💎", name: "gem", label: "Gema" },
  { icon: "💫", name: "diamond", label: "Diamante" },
  { icon: "🎌", name: "flag", label: "Bandeira" },
  { icon: "✅", name: "badge_check", label: "Verificado" },
  { icon: "🤖", name: "bot", label: "Bot" },
  { icon: "🧠", name: "brain", label: "Cérebro" },
  { icon: "🔥", name: "flame", label: "Chama" },
  { icon: "🎁", name: "gift", label: "Presente" },
  { icon: "🤘", name: "hand_metal", label: "Rock" },
  { icon: "💡", name: "lightbulb", label: "Ideia" },
  { icon: "🚀", name: "rocket", label: "Foguete" },
  { icon: "🎉", name: "party", label: "Festa" },
  { icon: "📢", name: "megaphone", label: "Megafone" },
  { icon: "🏅", name: "award", label: "Prêmio" },
  { icon: "🌟", name: "square_stack", label: "Destaque" },
];

